begin;
set local search_path=extensions,public;
select no_plan();
insert into rmc_auth_private.identities(id,role) values ('84000000-0000-4000-8000-000000000001','R');
select rmc_auth_api.write_cpf_source('84000000-0000-4000-8000-000000000001',1,1,0,1,decode(repeat('81',39),'hex'),array[1],array[decode(repeat('82',32),'hex')]);
select rmc_auth_private.stage_provisioning_phone('84000000-0000-4000-8000-000000000001',1,1,decode(repeat('83',41),'hex'),decode(repeat('84',32),'hex'));
select rmc_auth_api.claim_command('84000000-0000-4000-8000-000000000002','84000000-0000-4000-8000-000000000003',decode(repeat('85',32),'hex'),'PROVISION_IDENTITY',null,'84000000-0000-4000-8000-000000000001');
create temporary table r as select * from rmc_auth_api.reserve_provider('84000000-0000-4000-8000-000000000002',1,'84000000-0000-4000-8000-000000000004');
grant select on r to service_role;
set local role service_role;
select ok(not (select rmc_auth_api.admit_provider_attempt(command_id,lease_owner,fence,provider_subject,ownership_binding,identity_generation,true) from r),'legacy API name cannot dispatch without authorization');
select ok((select not dispatch_claimed from rmc_auth_private.provider_reservations),'denied legacy call has no dispatch effect');
select ok((select rmc_auth_api.record_provider_outcome(command_id,lease_owner,fence,provider_subject,ownership_binding,'OWNED') from r),'mechanism fixture confirms ownership only');
select ok(not (select rmc_auth_api.commit_provider_reservation(command_id,lease_owner,fence,gen_random_uuid(),'LOCAL') from r),'legacy API cannot commit owned target without fresh proof');
select ok((select provider_subject is null from rmc_auth_private.identities),'legacy denied commit cannot associate');
select ok(not (select rmc_auth_api.record_provisioning_conflict(command_id,lease_owner,0,provider_subject,ownership_binding,gen_random_uuid()) from r),'stale worker cannot escalate');
reset role;
create function pg_temp.fail_audit() returns trigger language plpgsql as $$begin raise exception using errcode='23514',message='SYNTHETIC_AUDIT_FAILURE'; end$$;
create trigger synthetic_audit_failure before insert on rmc_auth_private.audit_events for each row execute function pg_temp.fail_audit();
set local role service_role;
select throws_ok($$select rmc_auth_api.record_provisioning_conflict(command_id,lease_owner,fence,provider_subject,ownership_binding,gen_random_uuid()) from r$$,'23514','SYNTHETIC_AUDIT_FAILURE','audit failure rolls back conflict');
reset role;
select is((select count(*)::integer from rmc_auth_private.provisioning_escalations),0,'audit failure leaves no unaudited escalation');
select is((select count(*)::integer from rmc_auth_private.audit_outbox),0,'audit failure leaves no orphan outbox');
drop trigger synthetic_audit_failure on rmc_auth_private.audit_events;
set local role service_role;
select ok((select rmc_auth_api.record_provisioning_conflict(command_id,lease_owner,fence,provider_subject,ownership_binding,gen_random_uuid()) from r),'ownership conflict durably escalated');
select ok((select rmc_auth_api.record_provisioning_conflict(command_id,lease_owner,fence,provider_subject,ownership_binding,gen_random_uuid()) from r),'conflict replay idempotent');
reset role;
select is((select reason from rmc_auth_private.provisioning_escalations),'OWNERSHIP_CONFLICT','cause preserved immediately');
select is((select count(*)::integer from rmc_auth_private.audit_events),1,'single durable conflict audit');
select is((select count(*)::integer from rmc_auth_private.audit_outbox),1,'single conflict audit outbox');
set local role service_role;
select ok((rmc_auth_api.claim_provisioning_batch(gen_random_uuid(),3)->'commandIds')='[]'::jsonb,'escalated ownership conflict never retried');
reset role;
select ok(pg_get_functiondef('rmc_auth_api.admit_provider_attempt(uuid,uuid,bigint,uuid,uuid,bigint,boolean)'::regprocedure) like '%admit_authorized_provider_attempt%','legacy admission delegates authorized boundary');
select ok(pg_get_functiondef('rmc_auth_api.commit_provider_reservation(uuid,uuid,bigint,uuid,text)'::regprocedure) like '%commit_authorized_provider_reservation%','legacy commit delegates authorized boundary');
select ok(to_regprocedure('rmc_auth_private.admit_provider_attempt(uuid,uuid,bigint,uuid,uuid,bigint,boolean)') is not null,'unchecked mechanism outside exposed schema');
select ok(not has_function_privilege('anon','rmc_auth_private.admit_provider_attempt(uuid,uuid,bigint,uuid,uuid,bigint,boolean)','EXECUTE'),'private mechanism remains denied to browser');
select * from finish();
rollback;
