export const clientsCopy = {
  list: {
    caption: "Lista de clientes",
    loadError: "Não foi possível carregar os clientes de demonstração.",
    emptyTitle: "Nenhum cliente encontrado",
    emptyDescription: "Nenhum cliente corresponde aos critérios selecionados.",
    searchAriaLabel: "Buscar clientes",
    searchPlaceholder: "Buscar clientes...",
    cityFilterAriaLabel: "Filtrar clientes por cidade",
    cityFilterClearAriaLabel: "Limpar filtro de cidade",
    cityFilterPlaceholder: "Todas as cidades",
    citySearchAriaLabel: "Buscar cidade",
    citySearchPlaceholder: "Buscar cidade...",
    itemLabel: { singular: "cliente", plural: "clientes" },
  },
  vehicles: {
    caption: "Veículos do cliente",
    loadError: "Não foi possível carregar os veículos de demonstração.",
    emptyTitle: "Nenhum veículo encontrado",
    emptyDescription: "Nenhum veículo corresponde aos critérios selecionados.",
    searchAriaLabel: "Buscar veículos",
    searchWithoutDriverPlaceholder: "Buscar por placa ou veículo...",
    searchWithDriverPlaceholder: "Buscar por placa, veículo ou motorista...",
    filterAriaLabel: "Filtrar veículos por descrição",
    filterClearAriaLabel: "Limpar filtro de veículo",
    filterPlaceholder: "Todos os veículos",
    filterSearchAriaLabel: "Buscar descrição de veículo",
    filterSearchPlaceholder: "Buscar veículo...",
    itemLabel: { singular: "veículo", plural: "veículos" },
  },
  details: {
    fallbackTitle: "Cliente",
    loadingSubtitle: "Carregando dados do cliente.",
    unavailableSubtitle: "Cliente não disponível.",
    notFoundTitle: "Cliente não encontrado",
    notFoundDescription: "O cliente solicitado não está disponível.",
  },
} as const
