// Display names checked against the IBGE municipalities API on 2026-09-28.
export const unitCityNames: ReadonlyMap<string, string> = new Map([
  ["ARACARIGUAMA", "Ara\u00e7ariguama"],
  ["BALSAMO", "B\u00e1lsamo"],
  ["BAURU", "Bauru"],
  ["CAMPINA GRANDE DO SUL", "Campina Grande do Sul"],
  ["CANDIDO MOTA", "C\u00e2ndido Mota"],
  ["CEDRAL", "Cedral"],
  ["CORUMBATAI", "Corumbata\u00ed"],
  ["GALIA", "G\u00e1lia"],
  ["GASPAR", "Gaspar"],
  ["GUARA", "Guar\u00e1"],
  ["GUARAPUAVA", "Guarapuava"],
  ["GUARAREMA", "Guararema"],
  ["ILHOTA", "Ilhota"],
  ["JUNDIAI", "Jundia\u00ed"],
  ["LORENA", "Lorena"],
  ["LOUVEIRA", "Louveira"],
  ["MARILIA", "Mar\u00edlia"],
  ["MERIDIANO", "Meridiano"],
  ["MIRASSOL", "Mirassol"],
  ["ONDA VERDE", "Onda Verde"],
  ["ORLANDIA", "Orl\u00e2ndia"],
  ["PARANAGUA", "Paranagu\u00e1"],
  ["PARIQUERA-ACU", "Pariquera-A\u00e7u"],
  ["PIRACICABA", "Piracicaba"],
  ["PONTA GROSSA", "Ponta Grossa"],
  ["RIBEIRAO PRETO", "Ribeir\u00e3o Preto"],
  ["RUBINEIA", "Rubin\u00e9ia"],
  ["SANTA FE DO SUL", "Santa F\u00e9 do Sul"],
  ["SANTOPOLIS DO AGUAPEI", "Sant\u00f3polis do Aguape\u00ed"],
  ["SAO CARLOS", "S\u00e3o Carlos"],
  ["SAO JOSE DO RIO PRETO", "S\u00e3o Jos\u00e9 do Rio Preto"],
  ["UBERLANDIA", "Uberl\u00e2ndia"],
  ["URANIA", "Ur\u00e2nia"],
  ["VARZEA GRANDE", "V\u00e1rzea Grande"],
  ["VOTUPORANGA", "Votuporanga"],
])
